### ISSUE TITLE
Could not unwrap arc pointer

### ISSUE THREAD

**Issue by rrichardson** [cetra3/lorikeet#4]
Thanks for making a great tool. It is actually fun to use.  I've run into a problem and I've had a hard time debugging it so far.  When running these 3 jobs in parallel, I get this result: 
```
- name: lorikeet
  description: This step is shown if there was an error when reading, parsing or running steps
  pass: false
  error: Could not unwrap arc pointer
  duration: 0ms
```

I'm using this tool to validate an example constellation of web services during a deployment. Basically I am using it to smoke test the services.   Here is the test.yml 

```
  test.yml: |
    check_peerRed:
      http: http://service-red:8000
      match: |
        { "lalala" : "blah" }
    check_peerGreen:
      http: http://service-green:8000
      match: |
        { "lalala" : "blah" }
    check_peerBlue:
      http: http://service-blue:8000
      match: |
        { "lalala" : "blah" }
```

This is running in k8s,  so those URLs do work, but they return different json values.  So I expect these tests to fail,  but I didn't expect lorikeet to fail.

**Comment by rrichardson** [comment]
When trying to reduce my test set,  I dropped it down to a single test step.. and that worked.. kind of. 

```
- name: check_peer2
  pass: true
  output: {"peerResult":null,"result":{"responder":"service-red"}}
  duration: 29.735905ms
``` 

This should not have passed, since the command  was: 

```
    check_peer2:
      http: http://service-red:8000
      match: |
        { "lalala" : "blah" }
``` 

So I would have assume the test should have completed, but failed, since the two json blobs do not match.

**Comment by rrichardson** [comment]
Also.. I notice that even when running a single test step, it fails sometimes with the `Could not unwrap arc`  message.  But it happens all the time when running 2 or 3 steps.

**Comment by rrichardson** [comment]
Digging further.. it appears that this error is caused by using `match` instead of `matches` for the expect type.  

Now the matches step fails because my json blob can't create a valid regex.  Can I just do an exact string/json match without creating a regex?     More to the point,  what is the best way to validate json?

**Comment by rrichardson** [comment]
Nope.  It's two separate issues:   If I run more than one of these at a time, I get the same arc pointer error. 

```
    check_peer1:
      http: http://service-green:8000
      matches: responder
    check_peer2:
      http: http://service-red:8000
      matches: responder
    check_peer3:
      http: http://service-blue:8000
      matches: responder
```
If I run 1 at a time, using "requires" it seems to succeed more frequently, but it definitely seems like there is a race condition there.   If I add the requires to steps 2 and 3,  it works maybe 50% of the time.

**Comment by cetra3** [comment]
That's an interesting one! I've [refactored it](https://github.com/cetra3/lorikeet/commit/7b27e74f7f642e17826a3aac2a42aed14e6fc0c6) so there is no Arc anymore when running. Please see how you go against the current master and let me know if this solves your issue.

In terms of matching, you could use [`jmespath`](https://jmespath.org/) which allows you to check that the result is valid json and that there are terms you want in the result:

```yaml
check_peer2:
  value: |
    {"peerResult":null,"result":{"responder":"service-red"}}
  jmespath: result.responder
  matches: service-red
```

Output is as follows:

```yaml
- name: check_peer2
  pass: true
  output: "service-red"
  duration: 1.017299ms
```

**Comment by rrichardson** [comment]
That is quite a refactoring!   The new code works every time.   
The jmespath approach works well.   I am wondering:  Is there a way to validate multiple parts of the json blob?

**Comment by cetra3** [comment]
Ah, glad to see it's working!  I will close off this issue.

You can use the `step` type if you have multiple assertions you need to make on the same response.  Your first step should be the http request & then the other steps should be the `step` type:

```yaml
check_json:
  value: |
    {"part1": "part1result", "part2": "part2result"}

check_json_part1:
  step: check_json
  jmespath: part1
  matches: part1result

check_json_part2:
  step: check_json
  jmespath: part2
  matches: part2result
```

This should output like so:

```yaml
- name: check_json
  pass: true
  output: |
    {"part1": "part1result", "part2": "part2result"}
    
  duration: 0.435454ms

- name: check_json_part1
  pass: true
  output: "part1result"
  duration: 0.982837ms

- name: check_json_part2
  pass: true
  output: "part2result"
  duration: 0.882736ms
```
